apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccbd-app2-deployment
  labels:
    app: ccbd-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ccbd-app2
  template:
    metadata:
      labels:
        app: ccbd-app2
    spec:
      containers:
      - name: ccbd-app2
        image: veera491/ccbd-app2:latest
        ports:
        - containerPort: 5000
