apiVersion: v1
kind: Service
metadata:
  name: ccbd-app-service
  labels:
    app: ccbd-app
spec:
  type: NodePort
  selector:
    app: ccbd-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
